### ISSUE TITLE
The keycode in GTK4.0 made weird operation.

### ISSUE THREAD

**Issue by touchinglie** [Cutotopo/csnake#1]
I can't get available way to control the snake forward direction in wasd or arrows. Maybe the keycode isn't match? Where can I find the keycode reference?

**Comment by Cutotopo** [comment]
Hi, thanks for reporting this! Personally I can't reproduce this, but I think this may be due to how input is handled in the `key_pressed` function (using keycodes). I have now changed this function to use key values and compare them with GDK constants instead of some "magic numbers" found during development.

Let me know if this fixes input for you. In case it doesn't, could you please provide some details about your environment and your active keyboard layout(s), so i can try to reproduce the issue?

**Comment by touchinglie** [comment]
> Hi, thanks for reporting this! Personally I can't reproduce this, but I think this may be due to how input is handled in the `key_pressed` function (using keycodes). I have now changed this function to use key values and compare them with GDK constants instead of some "magic numbers" found during development.
> 
> Let me know if this fixes input for you. In case it doesn't, could you please provide some details about your environment and your active keyboard layout(s), so i can try to reproduce the issue?

Yes, I solve that by myself. When I check the exact reason, I also found the problem due to GTK4 keycodes: https://gitlab.gnome.org/GNOME/gtk/-/issues/2540

And after your fixed commit, the program works pretty will. 
Thanks for your work.

Otherwise, I want to add more feature in this game for my school work. (more requests v_v) Can I fork this repository and develop under the GNUv2 license?

**Comment by touchinglie** [comment]
If you want, I can contribute my code to this repository. But I see the code which is brief, and that truly is an basic independent game.

**Comment by Cutotopo** [comment]
> And after your fixed commit, the program works pretty will. Thanks for your work.

That is very nice to hear, absolutely no problem in asking me to fix my (admittedly bad) code.

> Otherwise, I want to add more feature in this game for my school work. (more requests v_v) Can I fork this repository and develop under the GNUv2 license?

Of course! I also wrote this code for a school project, so if you want to fork and work on it that's absolutely fantastic for me. After all, it is published under the GPLv2 for a reason!

> If you want, I can contribute my code to this repository. But I see the code which is brief, and that truly is an basic independent game.

If you could contribute your changes back to this repository, i would appreciate it a lot. Even if this program was written as a little school project, I'd love to see it improved and it could also be a nice learning opportunity for me, since I haven't been working in C for a while now.

**Comment by touchinglie** [comment]
> > And after your fixed commit, the program works pretty will. Thanks for your work.
> 
> That is very nice to hear, absolutely no problem in asking me to fix my (admittedly bad) code.
> 
> > Otherwise, I want to add more feature in this game for my school work. (more requests v_v) Can I fork this repository and develop under the GNUv2 license?
> 
> Of course! I also wrote this code for a school project, so if you want to fork and work on it that's absolutely fantastic for me. After all, it is published under the GPLv2 for a reason!
> 
> > If you want, I can contribute my code to this repository. But I see the code which is brief, and that truly is an basic independent game.
> 
> If you could contribute your changes back to this repository, i would appreciate it a lot. Even if this program was written as a little school project, I'd love to see it improved and it could also be a nice learning opportunity for me, since I haven't been working in C for a while now.

It's hard to expressing my gratitude. I would say reading the code and adding the features for this repository turly teached me a lot. I had finish my first school work based on your work, but in Windows for the moment. [SnakeGame](https://github.com/touchinglie/SnakeGame) Now I am trying to learn the gstreamer and pthread for contribute code which implements more features to this repository in cross platform.

**Comment by Cutotopo** [comment]
> It's hard to expressing my gratitude. I would say reading the code and adding the features for this repository turly teached me a lot. I had finish my first school work based on your work, but in Windows for the moment. [SnakeGame](https://github.com/touchinglie/SnakeGame) Now I am trying to learn the gstreamer and pthread for contribute code which implements more features to this repository in cross platform.

Sorry if I haven't replied earlier but I have been a little busy in the past days and ended up completely forgetting until I opened my email. Just had a look at your repo, very nice work! As soon as I have access to a Windows machine I'll try it. I think I'll also take this opportunity to learn a bit about the winapi, since I have never really used it directly.
